server:
  port: 8080
spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        provider:
          gateway-service:
            issuer-uri: http://dazzling_aryabhata:8089/auth/realms/fir
        registration:
          gateway-service:
            client-id: api-gateway
            client-secret: ZcvXUMw0HYGqk6gSMubjxyyOlPFQwd6Z
            authorization-grant-type: authorization_code
            redirect-uri: http://gateway:8090/login/oauth2/code/keycloak
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters: TokenRelay
      routes:
        - id: catalogRoute
          uri: lb://catalog-service/
          predicates:
            - Path=/api/v1/catalogs/**
  zipkin:
    enable: true
    base-url: http://zipkin:9411/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healtcheck:
      enable: true
    service-url:
      default-zone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
