server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters: TokenRelay
      routes:
        - id: catalogRoute
          uri: lb://catalog-service/
          predicates:
            - Path=/api/v1/catalogs/**
  zipkin:
    enable: true
    base-url: http://zipkin:9411/
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healtcheck:
      enable: true
    service-url:
      default-zone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
